{% set name = "nvector" %}
{% set version = "1.1.0" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nvector-{{ version }}.tar.gz
  sha256: 01658f2a8fde6186be8bfddb5e7d7b36bc8e3e31ba7dcfe4eee19ed600275756

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.2
    - scipy >=1.7.3
    - karney >=1.0

test:
  imports:
    - nvector
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/pbrod/nvector/
  summary: The nvector library is a suite of tools written in Python to solve geographical position calculations forked from nvector.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - opoplawski
    - pbrod
